fix: add libspeexdsp-dev dependency for mod_deepgram_transcribe build
mod_deepgram_transcribe requires speex/speex_resampler.h header file
which is provided by libspeexdsp-dev package.

The base image (srt2011/freeswitch-mod-audio-fork:latest) has the
runtime libraries but not the development headers needed for
compilation.

Added libspeexdsp-dev to the build dependencies to fix:
  fatal error: speex/speex_resampler.h: No such file or directory